documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "mkdocs.yml"
          - "examples/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "uv.lock"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
